// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ClickCounter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ClickCounter";
  readonly sourceName: "contracts/ClickCounter.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"clicker","type":"address"},{"indexed":false,"internalType":"uint256","name":"newCount","type":"uint256"}],"name":"Clicked","type":"event"},{"inputs":[],"name":"click","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"count","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b5060fc8061001b5f395ff3fe6080604052348015600e575f5ffd5b50600436106030575f3560e01c806306661abd1460345780637d55923d14604d575b5f5ffd5b603b5f5481565b60405190815260200160405180910390f35b60536055565b005b60015f5f8282546064919060a2565b90915550505f5460405190815233907ff7e8b307dd9151a22531391287117d703ae3480e5d287e15410155081dbb71159060200160405180910390a2565b8082018082111560c057634e487b7160e01b5f52601160045260245ffd5b9291505056fea26469706673582212207c343239697c0ea7fed3e84ea6595561dc7f53835aa82ce76613207da2d3b53764736f6c634300081e0033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106030575f3560e01c806306661abd1460345780637d55923d14604d575b5f5ffd5b603b5f5481565b60405190815260200160405180910390f35b60536055565b005b60015f5f8282546064919060a2565b90915550505f5460405190815233907ff7e8b307dd9151a22531391287117d703ae3480e5d287e15410155081dbb71159060200160405180910390a2565b8082018082111560c057634e487b7160e01b5f52601160045260245ffd5b9291505056fea26469706673582212207c343239697c0ea7fed3e84ea6595561dc7f53835aa82ce76613207da2d3b53764736f6c634300081e0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/ClickCounter.sol";
  readonly buildInfoId: "solc-0_8_30-0bbe9eaf53f300748c9c5a8b2f4636530f2949e4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ClickCounter"]: ClickCounter$Type;
    ["contracts/ClickCounter.sol:ClickCounter"]: ClickCounter$Type;
  }
}